<a href="https://colab.research.google.com/github/mohitt38/Pytorch/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)
    return out

In [2]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.3841],
        [0.4045],
        [0.3888],
        [0.3937],
        [0.3846],
        [0.3874],
        [0.3753],
        [0.3953],
        [0.3900],
        [0.3811]], grad_fn=<SigmoidBackward0>)

In [11]:
# Access the weights of the first Linear layer (index 0):
print("Weights of the first Linear layer:")
print(model.network[0].weight)

# Access the weights of the second Linear layer (index 2):
print("\nWeights of the second Linear layer:")
print(model.network[2].weight)

Weights of the first Linear layer:
Parameter containing:
tensor([[-0.3545, -0.0878, -0.1241, -0.1598,  0.0886],
        [ 0.0861,  0.0310,  0.4248,  0.1917,  0.0701],
        [-0.1761,  0.3633, -0.3108,  0.3322, -0.3825]], device='cuda:0',
       requires_grad=True)

Weights of the second Linear layer:
Parameter containing:
tensor([[ 0.1406, -0.1820,  0.5293]], device='cuda:0', requires_grad=True)


In [7]:
# model bias
# The Sequential model doesn't have a 'bias' attribute directly.
# Bias is in the individual layers within the Sequential model.
# Access the first Linear layer (index 0) to get its bias:
print("Bias of the first Linear layer:")
print(model.network[0].bias)

# Access the second Linear layer (index 2) to get its bias:
print("\nBias of the second Linear layer:")
print(model.network[2].bias)

Bias of the first Linear layer:
Parameter containing:
tensor([ 0.2112,  0.4312, -0.0446], requires_grad=True)

Bias of the second Linear layer:
Parameter containing:
tensor([-0.3160], requires_grad=True)


In [8]:
!pip install torchinfo

In [9]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00