<a href="https://colab.research.google.com/github/mohitt38/Pytorch/blob/main/Pytorch(Tensors).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU is avaliable")
  print(f'using Gpu: {torch.cuda.get_device_name(0)}')
else:
  print("GPu is not available. using cpu")

GPU is avaliable
using Gpu: Tesla T4


## Creating a Tensor


In [3]:
#using empty
a=torch.empty(2,3)

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
#using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#using rand
torch.rand(2,3)

tensor([[0.6491, 0.5168, 0.3093],
        [0.9392, 0.1391, 0.6057]])

In [8]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
#using tensor
torch.tensor([[1,4,5],[8,6,3]])

tensor([[1, 4, 5],
        [8, 6, 3]])

In [10]:
# other ways

#arange
print("using arange ->", torch.arange(0,10))

#linspace
print("using linspace ->", torch.linspace(0,10,5))

#using eye
print("using eye ->", torch.eye(5))

#using full
print("using full ->", torch.full((2,3), 5))

#using ones_like

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [11]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(x)

tensor([[              0,      1091621632,      1063892320],
        [136200807654464,               1,               6]])

In [14]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

Tensors Datatypes

In [17]:
x.dtype

torch.int64

In [18]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [20]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Matematical Operations

1. Scalar operation

In [21]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [22]:
#addition
x+2
x-2
x*3
x/3
(x*100)//3
((x*100)//3)%2

tensor([[1., 0.],
        [1., 1.]])

2. Elements wise operation

In [23]:
a = torch.rand(2,3)
b= torch.rand(2,3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [24]:
a+b
a-b
a*b
a/b
a**b
a% b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [25]:
c= torch.tensor([1,-2,-3,5])
# abs
torch.abs(c)

tensor([1, 2, 3, 5])

In [26]:
torch.neg(c)

tensor([-1,  2,  3, -5])

In [27]:
d = torch.tensor([9.5,1.4,6.8,4.2])

torch.round(d)

tensor([10.,  1.,  7.,  4.])

In [28]:
torch.floor(d)

tensor([9., 1., 6., 4.])

In [29]:
torch.clamp(d , min=2,max=3)

tensor([3., 2., 3., 3.])

Reduction operation

In [30]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [31]:
torch.sum(e)
torch.sum(e,dim=0) #col
torch.sum(e,dim=1) #row

tensor([15., 13.])

In [32]:
torch.mean(e)
torch.mean(e,dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [33]:
torch.median(e)

tensor(4.)

In [34]:
torch.max(e)
torch.min(e)

tensor(0.)

In [35]:
torch.prod(e)

tensor(0.)

In [36]:
torch.std(e)

tensor(3.1411)

In [37]:
torch.var(e)

tensor(9.8667)

In [38]:
torch.argmin(e)

tensor(5)

In [39]:
torch.argmax(e)

tensor(3)

4. Matrix Operation

In [40]:
f = torch.rand(2,3)
g = torch.rand(3,2)

print(f)
print(g)

tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])
tensor([[0.0447, 0.5123],
        [0.9051, 0.5989],
        [0.4450, 0.7278]])


In [41]:
torch.matmul(f,g)

tensor([[0.3437, 0.7574],
        [0.5375, 0.7492]])

In [42]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

torch.dot(vector1,vector2)

tensor(32)

In [43]:
f = torch.randint(size=(2,3), low=2, high=10)
f

tensor([[2, 4, 3],
        [3, 8, 5]])

In [44]:
torch.transpose(f, 0,1)

tensor([[2, 3],
        [4, 8],
        [3, 5]])

In [45]:
#determinant
h= torch.randint(size=(3,3), low=2, high=10, dtype=torch.float32)

torch.det(h)

tensor(124.0000)

In [46]:
torch.inverse(h)

tensor([[-0.4839,  0.3065,  0.4677],
        [ 0.1129, -0.1048,  0.0242],
        [ 0.2742, -0.0403, -0.2984]])

5. Comparison Operations

In [47]:
i = torch.randint(size=(2,3), low=2, high=10, dtype=torch.float64)
j = torch.randint(size=(2,3), low=2, high=10)

print(i)
print(j)

tensor([[9., 9., 7.],
        [8., 6., 4.]], dtype=torch.float64)
tensor([[2, 2, 4],
        [7, 4, 3]])


In [48]:
i>j

tensor([[True, True, True],
        [True, True, True]])

In [49]:
i<j

tensor([[False, False, False],
        [False, False, False]])

In [50]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [51]:
torch.log(i)

tensor([[2.1972, 2.1972, 1.9459],
        [2.0794, 1.7918, 1.3863]], dtype=torch.float64)

In [52]:
torch.exp(i)

tensor([[8103.0839, 8103.0839, 1096.6332],
        [2980.9580,  403.4288,   54.5982]], dtype=torch.float64)

In [53]:
torch.exp(j)

tensor([[   7.3891,    7.3891,   54.5981],
        [1096.6332,   54.5981,   20.0855]])

In [54]:
torch.sigmoid(j)

tensor([[0.8808, 0.8808, 0.9820],
        [0.9991, 0.9820, 0.9526]])

In [55]:
torch.softmax(i,dim=0)

tensor([[0.7311, 0.9526, 0.9526],
        [0.2689, 0.0474, 0.0474]], dtype=torch.float64)

In [56]:
torch.relu(i)

tensor([[9., 9., 7.],
        [8., 6., 4.]], dtype=torch.float64)

Inplacee Operation

In [57]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])
tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [58]:
m+n

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [59]:
m.add_(n)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [60]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [61]:
n

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [62]:
torch.relu(m)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [63]:
m.relu_()

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [64]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

Copying the tensors

In [65]:
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [66]:
b=a

In [67]:
b

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [68]:
a[0][0]=0

In [69]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [70]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [71]:
id(a)

136200808109616

In [72]:
id(b)

136200808109616

In [73]:
b = a.clone()

In [74]:
a[0][0]=50

In [75]:
a

tensor([[5.0000e+01, 8.9348e-01, 4.9744e-02],
        [1.7798e-01, 3.0110e-01, 1.8930e-01]])

In [76]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [77]:
id(a)

136200808109616

In [78]:
id(b)

136200808118976

Tensor operation on GPU

In [79]:
torch.cuda.is_available()

True

In [80]:
device = torch.device('cuda')

In [81]:
#creating a new tensor on GPU

torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [82]:
a = torch.rand(2,3)
a

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [83]:
b = a.to(device)

In [84]:
b+5

tensor([[5.9186, 5.2131, 5.3957],
        [5.6017, 5.4234, 5.5224]], device='cuda:0')